### ISSUE TITLE
Sugestão de indentificar os Tokens

### ISSUE THREAD

**Issue by Oufin** [bruno963852/dtre#1]
Salve! 

Cara essa sugestão consiste em ter uma indicação para os Tokens, pois concerteza em algum momento, o Mestre vai se esquecer de qual é qual em um momento de batalha grande! Nisso eu tenho duas sugestões:

1° - Um comando no qual colocaria uma borda de Token, que teria em um dos cantos, um número que o Mestre colocaria (não poderia ter mais que 3 caracteres), mais é falho pois sem o zoom em mapas grandes, seria difícil de ver.
2° - Um comando de rolagem de iniciativa, no qual o Bot lembre-se de cada rolagem o colocando em uma fila, que ele mandaria uma mensagem que diria algo tipo: - Vez de (...). E se houvesse como, a borda do token do personagem da vez, ficaria de outra cor, ou tivesse algum indicativo de qual token está com a vez.

Essas são as minhas sugestões, agradeço por lêr!

**Comment by bruno963852** [comment]
Vou fechar a issue só pra não deixar aberta, mas manter a sugestão anotada aqui.
