### ISSUE TITLE
Não é possível adicionar

### ISSUE THREAD

**Issue by MatheusOsh** [bruno963852/dtre#2]
![image](https://user-images.githubusercontent.com/74063707/98385373-a774d100-202d-11eb-8550-969c881ea903.png)
Apresentou esse erro ao adicionar

**Comment by bruno963852** [comment]
Vou deixar a justificativa aqui pro pessoal ficar ciente do que está acontecendo.

Minha carga de trabalho aumentou muito desde que comecei a fazer esse bot, portanto não estou podendo dedicar a atenção pra ele que eu gostaria, nunca imaginei que iria fazer tanto sucesso.
Agora que ele foi adicionado a 100 servidores o discord está exigindo algumas ações da minha parte para que o bot continue crescendo, as quais ainda não tive condição de parar pra fazer, ainda estou pensando em como vou prosseguir com ele...
Como o bot é open-source talvez eu faça um tutorial de como você mesmo pode criar uma cópia dele no discord pra rodar no seu próprio PC, ou então fazer alguma forma de arrecadação de fundos (talvez patreon ou apioa-se) até para custear a infraestrutura de servidor que eu terei de criar para então poder ampliar o bot sem ficar muito lento.

Vou manter essa issue aberta enquanto reflito sobre o assunto.

**Comment by OinkChops** [comment]
How would you let people know of the updates? I also use the bot and would love to support you in any way possible to keep it available for the public.

**Comment by bruno963852** [comment]
@OinkChops I would create a patreon page and post the updates there, also create a discord server only for backers. One thing i really wanted to know is how many users of the bot are english speakers. I even programmed the bot to send a form link with important questions and only 3 people answered...

**Comment by MatheusOsh** [comment]
Hey Bruno o7

On oinkchops server there are at least 20 active members using it daily. I am on her server and i did not see any form link though...

**Comment by bruno963852** [comment]
@MatheusOsh, that is awesome!
Maybe i did something wrong...
This is the form link:
https://docs.google.com/forms/d/e/1FAIpQLScKtpK07wcYJp3olo9psn_xPs-_OKmSZD1U02MXD2jPco-EMw/viewform?usp=sf_link

**Comment by bruno963852** [comment]
Solved
