### ISSUE TITLE
O BOT está Offline, não responde os comandos.

### ISSUE THREAD

**Issue by gaesyeah** [bruno963852/dtre#3]
Boa Noite Bruno!

Afinal, qual a situação atual do BOT? Dei uma pesquisada e vi que a 10 meses atrás o BOT estava de fato com problemas:
https://www.reddit.com/r/DTRE_BR/comments/ha6wad/rdtre_br_lounge/

Mas notei que o desenvolvedor fez alterações no BOT a 5 meses atrás. Não entendi, qual a situação atual? Gostaria muito de usá-lo mas infelizmente me deparei com esse problema. Até tentei replicar/copiar o BOT utilizando o "REPLIT" e o "DISCORD DEVELOPER PORTAL" mas não entendo nada de python. Tentei por ser open-source e não quero alterar isso, só desejo utilizar o BOT com meu grupo de amigos, na nossa mesa de RPG.

![erro](https://user-images.githubusercontent.com/90418594/132939008-a648282e-580c-4fc9-bffd-064f0c3a5e33.png)

Obrigado.

**Comment by bruno963852** [comment]
Olá, peço perdão pela demora na resposta. Infelizmente o trabalho tem consumido todo o meu tempo novamente e acabei por não perceer que estava com problema, vou tentar resolver assim que possível...
Apesar de tudo, não tenho nenhuma inteção de abandonar esse projeto por completo, assim que as coisas estiverem mais tranquilas vou reativar o desenvolvimento e trazer muitas novidades.

**Comment by gaesyeah** [comment]
Opa mano, tranquilo!

Fico feliz que o BOT ainda tem futuro pela frente, mas não se sinta culpado por estar sem tempo a ele devido a seu trampo, tenho certeza que é muito cansativo mas vale a pena. (sem falar que ao vc melhorar como profissional o BOT vai também evolui kkkkkkkk, bom pra todo mundo).

Pretendo trabalhar como desenvolvedor também, um dia eu chego lá. (na real eu já saí afirmando que vc trabalha com programação mas nem perguntei antes kkkkkk, o python é a sua favorita?

-> Inclusive...eu tenho usado bastante o fórum oficial do Tormenta20 esses últimos dias, posso fazer comercial do seu BOT por lá? não acho que vá ter tanto alcance mas o pessoal precisa conhece-lo!
-> Verifiquei aqui e o BOT já voltou a funcionar...Vlw man!
