### ISSUE TITLE
Off

### ISSUE THREAD

**Issue by LucasRPGs** [bruno963852/dtre#5]
O bot foi abandonado? Já faz muito tempo que ele está off.
Has the bot been abandoned? It's been a long time It's off .

**Comment by bruno963852** [comment]
E ae, mano. Subi o bot de novo. Ainda tô na luta pra arranjar tempo pra trabalhar mais nele, de vez em quando ele cai, aí quando eu vejo alguma mensagem do pessoal avisando eu subo de novo. Já tenho tudo planejado pra uma nova versão melhorada e tudo mais, mas o tempo tá complicado e o discord mudou algumas coisas  que preciso analisar, mas enfim, vamos torcer para no futuro breve as coisas se ajeitarem e eu ocnsiga executar o que estou pensando. No meio tempo, vai avisando quando o bot cair.

**Comment by LucasRPGs** [comment]
Muito obrigado seu bot ajuda MUITO nas sessões
